# Generated by Django 5.0.1 on 2025-01-27 11:48

import configurator.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название hdd')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/HDD/', verbose_name='Фото hdd')),
                ('capacity_gb', models.IntegerField(default=8000, verbose_name='Емкость, ГБ')),
                ('rpm', models.IntegerField(blank=True, null=True, verbose_name='Скорость вращения шпинделя, об/мин')),
                ('form_factor', models.CharField(default='3.5"', max_length=50, verbose_name='Форм-фактор')),
                ('interface', models.CharField(default='SATA-III', max_length=50, verbose_name='Интерфейс подключения')),
                ('warranty', models.IntegerField(default=12, verbose_name='Гарантия (мес.)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hdd', to='configurator.product')),
            ],
            bases=(configurator.models.AutoCreateProductMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ssd')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/SSD/', verbose_name='Фото ssd')),
                ('capacity_gb', models.IntegerField(default=1000, verbose_name='Емкость, ГБ')),
                ('form_factor', models.CharField(default='2.5"', max_length=50, verbose_name='Форм-фактор')),
                ('interface', models.CharField(default='SATA-III', max_length=50, verbose_name='Интерфейс подключения')),
                ('warranty', models.IntegerField(default=36, verbose_name='Гарантия (мес.)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssd', to='configurator.product')),
            ],
            bases=(configurator.models.AutoCreateProductMixin, models.Model),
        ),
    ]
