# Generated by Django 5.0.1 on 2024-12-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='dimensions_mm',
            field=models.CharField(default='199 x 120 x 41 мм', max_length=50, verbose_name='Размеры (ШхВхГ), мм'),
        ),
    ]
