# Generated by Django 5.0.1 on 2024-12-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_alter_case_bottom_fans_alter_case_drive_bays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='memory_size',
            field=models.IntegerField(default=8000, verbose_name='Объём памяти мб'),
        ),
    ]
