# Generated by Django 5.0.1 on 2025-01-27 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_hdd_ssd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='storage',
        ),
        migrations.AddField(
            model_name='build',
            name='HDD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurator.hdd'),
        ),
        migrations.AddField(
            model_name='build',
            name='SSD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurator.ssd'),
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
