# Generated by Django 5.0.1 on 2025-01-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_remove_build_storage_build_hdd_build_ssd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='HDD',
            new_name='hdd',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='SSD',
            new_name='ssd',
        ),
    ]
