# Generated by Django 5.0.1 on 2024-12-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_alter_gpu_dimensions_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='pcie_version',
            field=models.CharField(default='PCI Express 4.0', max_length=50, verbose_name='Версия PCIe'),
        ),
    ]
