# Generated by Django 5.0.1 on 2024-12-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_alter_gpu_memory_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='m2_slots',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество слотов M.2'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='sata_ports',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество SATA портов'),
        ),
    ]
