# Generated by Django 5.0.1 on 2024-12-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_alter_motherboard_pcie_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/cases/', verbose_name='Фото корпуса'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/CPU/', verbose_name='Фото CPU'),
        ),
        migrations.AlterField(
            model_name='cpucooler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/coolers/', verbose_name='Фото кулера'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/gpu/', verbose_name='Фото видеокарты'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/motherboards/', verbose_name='Фото материнской платы'),
        ),
        migrations.AlterField(
            model_name='os',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/os/', verbose_name='Фото операционной системы'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/psu/', verbose_name='Фото блока питания'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ram/', verbose_name='Фото ОЗУ'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/storage/', verbose_name='Фото накопителя'),
        ),
    ]
