# Generated by Django 5.0.1 on 2024-12-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_alter_case_type_alter_cpu_type_alter_cpucooler_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='spucooler',
            new_name='cpucooler',
        ),
    ]
