# Generated by Django 5.0.1 on 2024-12-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_rename_spucooler_build_cpucooler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='price',
        ),
    ]
